import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import { Toaster } from 'react-hot-toast'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Car Martz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {children:ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div><Toaster /></div>

        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
